//write mock data array of 20 items each with name, value and one random transaction type of either "expense" or "income"
export default [
  { name: "Salary", value: 2000, type: "income" },
  { name: "Rent", value: 1000, type: "expense" },
  { name: "Groceries", value: 500, type: "expense" },
  { name: "Bonus", value: 100, type: "income" },
  { name: "Car", value: 500, type: "expense" },
  { name: "Dividends", value: 100, type: "income" },
  { name: "Salary", value: 2000, type: "income" },
  { name: "Rent", value: 1000, type: "expense" },
  { name: "Groceries", value: 500, type: "expense" },
  { name: "Salary", value: 2000, type: "income" },
  { name: "Rent", value: 1000, type: "expense" },
  { name: "Groceries", value: 500, type: "expense" },
  { name: "Bonus", value: 100, type: "income" },
  { name: "Car", value: 500, type: "expense" },
  { name: "Dividends", value: 100, type: "income" },
  { name: "Salary", value: 2000, type: "income" },
  { name: "Rent", value: 1000, type: "expense" },
  { name: "Groceries", value: 500, type: "expense" },
]
